# Generated by Django 5.0.6 on 2024-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersuggestion',
            name='allergy_concern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersuggestion',
            name='flavor_suggestion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientinventory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonalflavor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
