# Generated by Django 5.1.3 on 2024-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate_house', '0002_alter_customersuggestion_allergy_concern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersuggestion',
            name='customer_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customersuggestion',
            name='flavor_suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
